version: '2.2'

services:
  cubesql-server:
     image: "mmtnrw/cubesql-55:latest"
     network_mode: host
     restart: always
     volumes:
       - "/share/CubeSQL/databases:/opt/databases"
       - "/share/CubeSQL/backups:/opt/backups"
       - "/share/CubeSQL/settings:/settings"
