version: '3'

services:
  cubesql-server:
    image: mmtnrw/cubesql-55:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "4430:4430"
    networks:
       - cubesql-net

networks:
  cubesql-net:
    driver: bridge
